#!/bin/bash

read -p "Hello, what is your name? " name
echo "Hello $name"

largestNum=0

for (( i=1; i<=5; i++ ))
do
        isNaN=true
        while $isNaN
        do
                read -p "Please enter number #$i: " number
                if [[ !($number =~ ^-?[0-9]+$) ]]; then
                        echo "Invalid input. Try again!"
                else
                        isNaN=false
                fi
        done
        if [ $number -gt $largestNum ]; then
                largestNum=$number
        fi
done
echo "The largest number is $largestNum!"
